name: Java CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Run unit tests
      run: mvn test --file pom.xml
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Tomcat
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.TOMCAT_HOST }}
        username: ${{ secrets.TOMCAT_USERNAME }}
        password: ${{ secrets.TOMCAT_PASSWORD }}
        source: "target/*.war"
        target: "/opt/tomcat/webapps/"
